## Player requests

### Create new player
POST  http://localhost:8080/api/players
Content-Type: application/json

{
  "nickName": "Denis",
  "email": "denis@example.com",
  "level": 5,
  "experience": 1000
}

### Get all players
GET http://localhost:8080/api/players
Accept: application/json

### Get player by ID
GET http://localhost:8080/api/players/1
Accept: application/json

### Delete player by ID
DELETE http://localhost:8080/api/players/1

## Games requests

### Add game to player
POST http://localhost:8080/api/games/player/1
Content-Type: application/json

{
  "gameTitle": "Fallout 2",
  "gameGenre": "Isometric RPG",
  "gameDescription": "Fallout 2: A Post Nuclear Role Playing Game is the sequel to the original Fallout."
}

### Get all games
GET http://localhost:8080/api/games
Accept: application/json

### Get game by ID
GET http://localhost:8080/api/games/2
Accept: application/json

### Delete game by ID
DELETE http://localhost:8080/api/games/2

## Achievements requests

### Add new achievement to player
POST http://localhost:8080/api/achievements
Content-Type: application/json

{
  "achievementName": "World to dust",
  "achievementDescription": "You have destroyed Enclave secret Oil Rig base, nice work!",
  "dateAchieved": "2025-04-03T12:00:00",
  "player": {"id" : 2},
  "game": {"id" :  1}
}

### Get all achievements
GET http://localhost:8080/api/achievements
Accept: application/json

### Get achievement by ID
GET http://localhost:8080/api/achievements/3
Accept: application/json

### Delete achievement by ID
DELETE http://localhost:8080/api/achievements/1

## Items requests

### Add new inventory item to player
POST http://localhost:8080/api/inventory
Content-Type: application/json

{
  "itemName": "T-51 power armour helmet",
  "itemDescription": "Helmet of a legendary armour used in vast amount of battles, it is pretty rusty!",
  "cost": 1000.0,
  "player": {"id" : 2},
  "game": {"id" : 1}
}

### Get all inventory items
GET http://localhost:8080/api/inventory
Accept: application/json

### Get inventory item by ID
GET http://localhost:8080/api/inventory/1
Accept: application/json

### Delete inventory item by ID
DELETE http://localhost:8080/api/inventory/1